#!/usr/bin/env bash
# lib/wallpaper.sh: GNOME desktop wallpaper.
#
# Personal profile: a rotating slideshow of Porsche 911 GT3 RS wallpapers,
# matching the GT3 RS fastfetch splash. The vortex profile leaves whatever
# wallpaper the machine already has alone, because Vortex members did not sign
# up for somebody else's taste in cars.
#
# Stock GNOME only, via gsettings. No compositor or WM logic.

[[ -n "${_VXO_WALLPAPER_SOURCED:-}" ]] && return 0
_VXO_WALLPAPER_SOURCED=1

# shellcheck source=lib/common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

VXO_WALLPAPER_SRC="$VXO_ASSETS/wallpapers"
VXO_WALLPAPER_DIR="$HOME/.local/share/backgrounds/vortex-onboarding"
VXO_WALLPAPER_XML="$VXO_WALLPAPER_DIR/gt3rs-slideshow.xml"

# Seconds each image is shown, and the cross-fade length between them.
VXO_WALLPAPER_DURATION="1800.0"   # 30 minutes
VXO_WALLPAPER_TRANSITION="5.0"

vxo_wallpaper() {
    # Mode: slideshow (default) | static | none. Set by --wallpaper=.
    local mode="${VXO_WALLPAPER_MODE:-slideshow}"

    if [[ "$mode" == "none" ]]; then
        log_skip "wallpaper: disabled with --wallpaper=none"
        return 0
    fi

    if [[ "${VXO_PROFILE:-vortex}" != "personal" ]]; then
        stage_abort "wallpaper: GT3 RS wallpapers are personal-profile only. The vortex profile leaves your existing wallpaper untouched."
        return 0
    fi

    _vxo_wallpaper_guard || return 0
    _vxo_wallpaper_stage_images

    case "$mode" in
        slideshow) _vxo_wallpaper_write_xml; _vxo_wallpaper_apply "$VXO_WALLPAPER_XML" ;;
        static)    _vxo_wallpaper_apply "$(_vxo_wallpaper_first_image)" ;;
        *)         log_error "Unknown wallpaper mode: $mode (expected slideshow, static or none)"; return 1 ;;
    esac

    _vxo_wallpaper_register_in_picker
}

# GNOME settings need a session bus. Over SSH or in CI there isn't one, and
# gsettings would either fail or write to a throwaway dbus session.
_vxo_wallpaper_guard() {
    if ! have gsettings; then
        stage_abort "wallpaper: gsettings not found, skipping."
        return 1
    fi
    if [[ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ]]; then
        stage_abort "wallpaper: no DBus session (running over SSH?). Re-run inside a desktop session with ./install.sh --only=wallpaper"
        return 1
    fi
    return 0
}

# The staged paths, derived from the bundled sources rather than globbed from
# the destination. Globbing the destination breaks --dry-run, where nothing has
# actually been copied yet, and would produce an empty slideshow.
#
# Note: this module never calls `die`. `die` exits, and the wallpaper stage runs
# in "soft" mode, so an exit here would take the whole installer down with it.
# Errors return non-zero so run_stage can report and carry on.
_vxo_wallpaper_image_list() {
    local src found=0
    for src in "$VXO_WALLPAPER_SRC"/*.jpg; do
        [[ -e "$src" ]] || continue
        printf '%s\n' "$VXO_WALLPAPER_DIR/$(basename "$src")"
        found=1
    done
    ((found == 1))
}

# Copy the bundled wallpapers into the user's own backgrounds dir. They must
# live outside the repo, or deleting the clone silently blanks the desktop.
_vxo_wallpaper_stage_images() {
    local count=0 src
    run mkdir -p "$VXO_WALLPAPER_DIR"
    for src in "$VXO_WALLPAPER_SRC"/*.jpg; do
        [[ -e "$src" ]] || continue
        local dest
        dest="$VXO_WALLPAPER_DIR/$(basename "$src")"
        if [[ -f "$dest" ]] && cmp -s "$src" "$dest"; then
            log_skip "wallpaper: $(basename "$src") already staged"
        else
            run install -m 0644 "$src" "$dest"
            log_ok "wallpaper: staged $(basename "$src")"
        fi
        count=$((count + 1))
    done
    if ((count == 0)); then
        log_error "No wallpapers found in $VXO_WALLPAPER_SRC"
        return 1
    fi
    log_info "wallpaper: $count image(s) in $VXO_WALLPAPER_DIR"
}

_vxo_wallpaper_first_image() {
    _vxo_wallpaper_image_list | head -n 1
}

# GNOME's slideshow format: a ring of <static> holds joined by <transition>
# cross-fades. The last transition points back at the first image so it loops.
_vxo_wallpaper_write_xml() {
    local images=()
    mapfile -t images < <(_vxo_wallpaper_image_list)
    if ((${#images[@]} == 0)); then
        log_error "No wallpapers available to build a slideshow from"
        return 1
    fi

    local xml i next
    xml=$'<?xml version="1.0" ?>\n'
    xml+=$'<!-- Generated by vortex-onboarding. Edit install.sh --only=wallpaper instead. -->\n'
    xml+=$'<background>\n'
    xml+=$'  <starttime>\n    <year>2026</year>\n    <month>01</month>\n    <day>01</day>\n'
    xml+=$'    <hour>00</hour>\n    <minute>00</minute>\n    <second>00</second>\n  </starttime>\n'

    for i in "${!images[@]}"; do
        next=$(( (i + 1) % ${#images[@]} ))
        xml+="  <static>"$'\n'
        xml+="    <duration>${VXO_WALLPAPER_DURATION}</duration>"$'\n'
        xml+="    <file>${images[$i]}</file>"$'\n'
        xml+="  </static>"$'\n'
        xml+="  <transition type=\"overlay\">"$'\n'
        xml+="    <duration>${VXO_WALLPAPER_TRANSITION}</duration>"$'\n'
        xml+="    <from>${images[$i]}</from>"$'\n'
        xml+="    <to>${images[$next]}</to>"$'\n'
        xml+="  </transition>"$'\n'
    done
    xml+=$'</background>\n'

    if [[ "${VXO_DRY_RUN:-0}" == "1" ]]; then
        log_info "[dry-run] would write slideshow of ${#images[@]} images to $VXO_WALLPAPER_XML"
        return 0
    fi

    if [[ -f "$VXO_WALLPAPER_XML" ]] && [[ "$(cat "$VXO_WALLPAPER_XML")" == "$xml" ]]; then
        log_skip "wallpaper: slideshow XML already current"
        return 0
    fi

    mkdir -p "$(dirname "$VXO_WALLPAPER_XML")"
    printf '%s' "$xml" >"$VXO_WALLPAPER_XML"
    log_ok "wallpaper: slideshow of ${#images[@]} images, ${VXO_WALLPAPER_DURATION%.*}s each"
}

# Record what the wallpaper was before we touch it, so the change is reversible.
_vxo_wallpaper_backup() {
    local out
    out="$VXO_BACKUP_DIR/wallpaper-$(date +%s).txt"
    [[ "${VXO_DRY_RUN:-0}" == "1" ]] && return 0
    {
        printf '# Previous wallpaper settings. Restore with:\n'
        printf '#   gsettings set org.gnome.desktop.background picture-uri "<value>"\n'
        printf 'picture-uri %s\n'      "$(gsettings get org.gnome.desktop.background picture-uri 2>/dev/null)"
        printf 'picture-uri-dark %s\n' "$(gsettings get org.gnome.desktop.background picture-uri-dark 2>/dev/null)"
        printf 'picture-options %s\n'  "$(gsettings get org.gnome.desktop.background picture-options 2>/dev/null)"
    } >"$out" 2>/dev/null || true
    log_info "wallpaper: previous settings saved to $out"
}

_vxo_wallpaper_apply() {
    local target="$1"
    local uri="file://$target"

    local current
    current="$(gsettings get org.gnome.desktop.background picture-uri 2>/dev/null || echo '')"
    if [[ "$current" == "'$uri'" ]]; then
        log_skip "wallpaper: already set"
        return 0
    fi

    _vxo_wallpaper_backup

    # Both light and dark, or the desktop reverts when the theme switches.
    run gsettings set org.gnome.desktop.background picture-uri "$uri"
    run gsettings set org.gnome.desktop.background picture-uri-dark "$uri"
    run gsettings set org.gnome.desktop.background picture-options 'zoom'
    run gsettings set org.gnome.desktop.background primary-color '#000000'

    # Match the lock screen so it doesn't stay on Ubuntu's default.
    run gsettings set org.gnome.desktop.screensaver picture-uri "$uri" 2>/dev/null || true
    run gsettings set org.gnome.desktop.screensaver picture-options 'zoom' 2>/dev/null || true

    log_ok "wallpaper: applied $(basename "$target")"
}

# Make the set selectable in Settings → Appearance, not just applied blindly.
_vxo_wallpaper_register_in_picker() {
    local dir="$HOME/.local/share/gnome-background-properties"
    local file="$dir/vortex-onboarding-gt3rs.xml"
    local content
    content=$(cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
<!-- Generated by vortex-onboarding -->
<wallpapers>
  <wallpaper deleted="false">
    <name>Porsche 911 GT3 RS (slideshow)</name>
    <filename>${VXO_WALLPAPER_XML}</filename>
    <options>zoom</options>
    <pcolor>#000000</pcolor>
    <scolor>#000000</scolor>
    <shade_type>solid</shade_type>
  </wallpaper>
</wallpapers>
EOF
)
    if [[ "${VXO_DRY_RUN:-0}" == "1" ]]; then
        log_info "[dry-run] would register the slideshow in the GNOME wallpaper picker"
        return 0
    fi
    mkdir -p "$dir"
    if [[ -f "$file" ]] && [[ "$(cat "$file")" == "$content" ]]; then
        log_skip "wallpaper: already registered in the picker"
        return 0
    fi
    printf '%s\n' "$content" >"$file"
    log_ok "wallpaper: registered in Settings → Appearance"
}
